name: Rust

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - name: Build
#      run: cargo build --verbose --release
#    - name: Run tests
#      run: cargo test --verbose
    - name: Build
      run: docker run -v "$(pwd):/" rust:slim-bullseye sh -c "cargo build --release --target=x86_64-unknown-linux-gnu"
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@v0.8.0
      with:
        local: target/x86_64-unknown-linux-gnu/release/offline_rustbot
        remote: bot/offline_rustbot
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
